title: Elwin Ehlers
logo: "/assets/images/Elwin.jpg"
description: I like well-structured systems and good documentation.
google-site-verification: "ZZOEcA0ewLEfkH9g1UkLq-2IcGL_qnPdUULgMl7TlTo"
show_downloads: true
theme: jekyll-theme-minimal
