title: Elwin Ehlers
logo: "/assets/images/Elwin.jpg"
description: Linux Sysadmin · Windows Admin (MCSA 2012) · Self-hosted Infrastructure
google-site-verification: "ZZOEcA0ewLEfkH9g1UkLq-2IcGL_qnPdUULgMl7TlTo"
show_downloads: false
theme: jekyll-theme-minimal
